# -------------------------------------
# Site settings
title: Laura + Austin
description: Wedding website of Laura Kelly and Austin Reed

# -------------------------------------
# Welcome message

welcome_message: "We would like to extend a warm and heartfelt welcome to everyone who has supported us throughout the years. We would not be here without your constant love and encouragement, and we can't thank you enough. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc nec nunc scelerisque, in blandit nisl congue. Vivamus vel diam posuere, scelerisque risus sit amet, ultrices ante. Phasellus nec turpis a elit dictum pharetra quis in tellus. Praesent condimentum odio ex, ultricies efficitur lorem ornare eu. Donec pretium lorem sagittis, tempus nunc non, pulvinar sapien. Nam rhoncus sagittis nunc, ac sagittis ex commodo nec."
